version: 2
# orbs:
#   aws-cli: circleci/aws-cli@2.0
jobs:
  # aws-cli-cred-setup:
  #   executor: aws-cli/default
  #   steps:
  #     - aws-cli/setup:
  #         aws-access-key-id: AWS_ACCESS_KEY
  #         aws-secret-access-key: AWS_ACCESS_SECRET
  #         aws-region: AWS_REGION_NAME
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
      - run:
          name: Install awscli
          command: pip install awscli
      - run:
          name: Connect to ECR
          command: |
            export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY"
            export AWS_SECRET_ACCESS_KEY="$AWS_ACCESS_SECRET"
            export AWS_DEFAULT_REGION="$AWS_REGION_NAME"
            aws configure list

      # - run:
      #     name: Build application Docker image
      #     command: |
      #       cd src
      #       docker-compose build
      # - deploy:
      #     name: Push application Docker image
      #     command: |
      #       docker images
workflow:
  build:
    jobs:
      - build