version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu-2204:2022.04.2
      
    steps:
      - checkout
      - run:
          working_directory: ~/src/
          name: Run build
          command: docker-compose build


workflows:
  sample:
    jobs:
      - build
