version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          working_directory: ~/src/
          name: Run build
          command: |
            docker login -u olehratinskiy -p qwertyuiop123456789
            docker-compose build
          
workflows:
  sample:
    jobs:
      - build