version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.12.0
      - run:
          name: Install awscli
          command: pip install awscli
      - run:
          name: Build application Docker image
          command: |
            cd src
            docker-compose build
            docker images
      - deploy:
          name: Push application Docker image
          command: |        
            aws configure set region $AWS_REGION_NAME --profile $AWS_USER_NAME 
            aws configure set aws_access_key_id $AWS_ACCESS_KEY --profile $AWS_USER_NAME 
            aws configure set aws_secret_access_key $AWS_ACCESS_SECRET --profile $AWS_USER_NAME

            P=$(aws ecr-public get-login-password --profile $AWS_USER_NAME)

            docker login --username AWS -p $P public.ecr.aws/h2y1x0t6

            docker tag eshop/webspa:webspa public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker tag eshop/webmvc:webmvc public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker tag eshop/webshoppingagg:webshoppingagg public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker tag eshop/ordering.signalrhub:ordering.signalrhub public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker tag eshop/mobileshoppingagg:mobileshoppingagg public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker tag eshop/ordering.api:ordering.api public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker tag eshop/ordering.backgroundtasks:ordering.backgroundtasks public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker tag eshop/payment.api:payment.api public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker tag eshop/basket.api:basket.api public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker tag eshop/catalog.api:catalog.api public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker tag eshop/identity.api:identity.api public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker tag eshop/webhooks.client:webhooks.client public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker tag eshop/webhooks.api:webhooks.api public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker tag eshop/webstatus:webstatus public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker tag mcr.microsoft.com/dotnet/sdk:mcr.microsoft.com/dotnet/sdk public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker tag mcr.microsoft.com/dotnet/aspnet:mcr.microsoft.com/dotnet/aspnet public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images

workflow:
  build:
    jobs:
      - build