version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.12.0
      - run:
          name: Install awscli
          command: pip install awscli
            
      #       aws configure list
      # - run:
      #     name: Build application Docker image
      #     command: |
      #       cd src
      #       docker-compose build
      - deploy:
          name: Push application Docker image
          command: |        
            docker pull alpine
            docker images
            aws configure list
            ls
            echo 1
            
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
            export AWS_SECRET_ACCESS_KEY=$AWS_ACCESS_SECRET
            export AWS_DEFAULT_REGION=$AWS_REGION_NAME
            echo 1

            aws configure set region $AWS_REGION_NAME --profile Oleh 
            aws configure set aws_access_key_id $AWS_ACCESS_KEY --profile Oleh 
            aws configure set aws_secret_access_key $AWS_ACCESS_SECRET --profile Oleh 
            echo 1

            P=$(aws ecr get-login-password --profile Oleh)
            echo $P
            docker login --username AWS -p $P public.ecr.aws
            docker login
            echo 1
            # docker tag alpine:latest public.ecr.aws/h2y1x0t6/eshoponcontainers_images
            # docker push public.ecr.aws/h2y1x0t6/eshoponcontainers_images
workflow:
  build:
    jobs:
      - build