version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.12.0
      - run:
          name: Install awscli
          command: pip install awscli
  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run:
          name: Connect to instance
          command: |
            aws

workflow:
  build and deploy:
    jobs:
      - build
      - deploy