version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu-2204:2022.04.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
      
    steps:
      - checkout
      - run:
          working_directory: ~/src/
          name: Run build
          command: docker-compose build


workflows:
  sample:
    jobs:
      - build:
          context:
            - build-env-vars
            - docker-hub-creds