version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          working_directory: ~/src/
          name: Run build
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose build
          
workflows:
  sample:
    jobs:
      - build