version: "3.2"

services:

  seq:
    image: datalust/seq:latest

  nosqldata:
    image: mongo

  basketdata:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity-api:
    image: public.ecr.aws/h2y1x0t6/eshoponcontainers_images:identity.api
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

  basket-api:
    image: public.ecr.aws/h2y1x0t6/eshoponcontainers_images:basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basketdata
      - identity-api
      - rabbitmq

  catalog-api:
    image: public.ecr.aws/h2y1x0t6/eshoponcontainers_images:catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - rabbitmq

  ordering-api:
    image: public.ecr.aws/h2y1x0t6/eshoponcontainers_images:ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - rabbitmq

  ordering-backgroundtasks:
    image: public.ecr.aws/h2y1x0t6/eshoponcontainers_images:ordering.backgroundtasks
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.BackgroundTasks/Dockerfile
    depends_on:
      - rabbitmq

  payment-api:
    image: public.ecr.aws/h2y1x0t6/eshoponcontainers_images:payment.api
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq

  webhooks-api:
    image: public.ecr.aws/h2y1x0t6/eshoponcontainers_images:webhooks.api
    build:
      context: .
      dockerfile: Services/Webhooks/Webhooks.API/Dockerfile

  mobileshoppingapigw:
    image: envoyproxy/envoy:v1.11.1

  mobileshoppingagg:
    image: public.ecr.aws/h2y1x0t6/eshoponcontainers_images:mobileshoppingagg
    build:
      context: .
      dockerfile: ApiGateways/Mobile.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  webshoppingagg:
    image: public.ecr.aws/h2y1x0t6/eshoponcontainers_images:webshoppingagg
    build:
      context: .
      dockerfile: ApiGateways/Web.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  ordering-signalrhub:
    image: public.ecr.aws/h2y1x0t6/eshoponcontainers_images:ordering.signalrhub
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.SignalrHub/Dockerfile
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  webstatus:
    image: public.ecr.aws/h2y1x0t6/eshoponcontainers_images:webstatus
    build:
      context: .
      dockerfile: Web/WebStatus/Dockerfile

  webspa:
    image: public.ecr.aws/h2y1x0t6/eshoponcontainers_images:webspa
    build:
      context: .
      dockerfile: Web/WebSPA/Dockerfile
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12.0}
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webmvc:
    image: public.ecr.aws/h2y1x0t6/eshoponcontainers_images:webmvc
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webhooks-client:
    image: public.ecr.aws/h2y1x0t6/eshoponcontainers_images:webhooks.client
    build:
      context: .
      dockerfile: Web/WebhookClient/Dockerfile
    depends_on:
      - webhooks-api

  webshoppingapigw:
    image: envoyproxy/envoy:v1.11.1