version: "3.2"

services:

  seq:
    image: datalust/seq:latest

  nosqldata:
    image: mongo

  basketdata:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity-api:
    image: eshop/identity.api:linux-latest
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

  basket-api:
    image: eshop/basket.api:linux-latest
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basketdata
      - identity-api
      - rabbitmq

  catalog-api:
    image: eshop/catalog.api:linux-latest
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - rabbitmq

  ordering-api:
    image: eshop/ordering.api:linux-latest
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - rabbitmq

  ordering-backgroundtasks:
    image: eshop/ordering.backgroundtasks:linux-latest
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.BackgroundTasks/Dockerfile
    depends_on:
      - rabbitmq

  payment-api:
    image: eshop/payment.api:linux-latest
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq

  webhooks-api:
    image: eshop/webhooks.api:linux-latest
    build:
      context: .
      dockerfile: Services/Webhooks/Webhooks.API/Dockerfile

  mobileshoppingapigw:
    image: envoyproxy/envoy:v1.11.1

  mobileshoppingagg:
    image: eshop/mobileshoppingagg:linux-latest
    build:
      context: .
      dockerfile: ApiGateways/Mobile.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  webshoppingagg:
    image: eshop/webshoppingagg:linux-latest
    build:
      context: .
      dockerfile: ApiGateways/Web.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  ordering-signalrhub:
    image: eshop/ordering.signalrhub:linux-latest
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.SignalrHub/Dockerfile
    depends_on:
      - nosqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  webstatus:
    image: eshop/webstatus:linux-latest
    build:
      context: .
      dockerfile: Web/WebStatus/Dockerfile

  webspa:
    image: eshop/webspa:linux-latest
    build:
      context: .
      dockerfile: Web/WebSPA/Dockerfile
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12.0}
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webmvc:
    image: eshop/webmvc:linux-latest
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webhooks-client:
    image: eshop/webhooks.client:linux-latest
    build:
      context: .
      dockerfile: Web/WebhookClient/Dockerfile
    depends_on:
      - webhooks-api

  webshoppingapigw:
    image: envoyproxy/envoy:v1.11.1